# 默认LLM Config
# 用于管理Agent构造新Agent实例时自动拼接到配置中
# （管理Agent生成的新Agent配置并不包含LLM Config）


api_type: "ollama"
base_url: "http://192.168.30.16:11434/api"
model: "qwq:32b"
max_tokens: 8192
temperature: 0.1
timeout: 600