# Date: 2025/04/27
# 该文件用于描述技能的使用方法，以及技能包含的提示词。

# 技能的简要作用描述，Agent所有可选技能与工具的简要描述会被组装在available_skills_and_tools中

use_guide:
  skill_name: "ask_info"
  description:
    "
    该技能用于获取MAS中的各种信息，包括task_state、stage_state和其他Agent的信息。
    **一般该技能的使用（ask_info 系统信息查询）是为了更好地执行任务管理技能task_manager**
    该技能会经由SyncState，将查询结果通过Message传递回你。你将被添加一个process_message用于消化它。
    
    具体可执行的查询操作包括：
    
    1. 查看自身所管理的task_state及其附属stage_state的信息 （不包括任务共享消息池信息）
    2. 查看自身所参与的task_state及参与的stage_state的信息 （不包括任务共享消息池信息）
    3. 查看指定task_state的详细信息 （不包括附属阶段信息）  
    4. 查看指定stage_stage的信息
    
    5. 查看MAS中所有Agent的profile （不包括持续性记忆）
    6. 查看Team中所有Agent的profile （不包括持续性记忆）
    7. 查看指定task_id的task_group中所有Agent的profile （不包括持续性记忆）
    8. 查看指定stage下协作的所有Agent的profile （不包括持续性记忆）
    9. 查看指定agent_id或多个agent_id的详细agent_state信息  
    10. 获取系统中所有可实例化的agent配置信息（包含已激活和未激活的），即 available_agents_config
    
    **一次ask_info只允许使用其中一种查询，使用ask_info时请在step.step_intention与step.text_content中清楚写明意图与具体查询类型**
    "

# 技能实际调用的提示词  
use_prompt:  
  skill_name: "ask_info"  
  skill_prompt: |
    **你现在正在执行ask_info技能，你可以获取系统中的各种信息，包括任务状态、阶段状态和其他Agent的信息。**
    通过ask_info，你可以获取以下类型的信息：

    - 任务相关信息：
       - 获取你管理的任务及其附属阶段的信息，不包括任务共享消息池信息 (managed_task_and_stage_info)
       - 获取你参与的任务及参与的阶段的信息，不包括任务共享消息池信息 (assigned_task_and_stage_info)
       - 获取指定任务的详细信息，不包括附属阶段信息 (task_info)
       - 获取指定阶段的详细信息 (stage_info)

    - Agent相关信息：
       - 获取多智能体系统MAS中所有Agent的基本信息，不包括持续性记忆 (all_agents)
       - 获取团队Team中所有Agent的基本信息，不包括持续性记忆 (team_agents)
       - 获取指定任务群组中所有Agent的信息，需要指定task_id，不包括持续性记忆 (task_agents)
       - 获取指定阶段下协作的所有Agent的信息，需要指定task_id与stage_id，不包括持续性记忆 (stage_agents)
       - 获取指定Agent的详细状态信息 (agent)

    - 获取系统中所有可实例化的agent配置信息（包含已激活和未激活的）(available_agents_config)
      - 你可以通过该类型获取mas/role_config目录下所有agent的配置（如name/role/profile/skills/tools等字段）

    **根据你当前步骤意图，仔细按照return_format中的格式返回具体指令**

  return_format: |
    **输出查询指令格式为字典，根据不同的查询类型，填充具体指令的字段值：**
    
    - 获取系统中所有可实例化的agent配置信息 (available_agents_config)，需要填充一个字段：
      {
        "type": "available_agents_config"
      }
    
    - 获取你管理的任务及其附属阶段的信息 (managed_task_and_stage_info)，需要填充一个字段：
      {
        "type": "managed_task_and_stage_info",
      }
     
    - 获取你参与的任务及参与的阶段的信息 (assigned_task_and_stage_info)，需要填充一个字段:
      {
        "type": "assigned_task_and_stage_info",
      }
    
    - 获取指定任务的详细信息 (task_info)，需要填充两个字段：
      {
        "type": "task_info",
        "task_id": "<task_id>"  # 任务ID
      }
    
    - 获取指定阶段的详细信息 (stage_info)，需要填充三个字段：
      {
        "type": "stage_info",
        "task_id": "<task_id>",  # 任务ID
        "stage_id": "<stage_id>"  # 阶段ID
      }
    
    - 获取多智能体系统MAS中所有Agent的基本信息 (all_agents)，需要填充一个字段：
      {
        "type": "all_agents",
      }
    
    - 获取团队Team中所有Agent的基本信息 (team_agents)，需要填充两个字段：
      {
        "type": "team_agents",
        "team_id": "<team_id>"  # 团队ID
      }
    
    - 获取指定任务群组中所有Agent的信息 (task_agents)，需要填充两个字段：
      {
        "type": "task_agents",
        "task_id": "<task_id>"  # 任务ID
      }
    
    - 获取指定阶段下协作的所有Agent的信息 (stage_agents)，需要填充三个字段：
      {
        "type": "stage_agents",
        "task_id": "<task_id>",  # 任务ID
        "stage_id": "<stage_id>"  # 阶段ID
      }
    
    - 获取指定Agent的详细状态信息 (agent)，需要填充两个字段：
      {
        "type": "agent",
        "agent_id": [<agent_id>,<agent_id>,...]  # 包含Agent ID的列表 List[str]
      }

    **请将你的指令构造结果用<ask_info>和</ask_info>标记，不要将其放在代码块中，否则将无法被系统识别。**返回示例： 
     <ask_info>
     具体查询指令...
     </ask_info>
