# Date: 2025/03/31
# 该文件用于描述技能的使用方法，以及技能包含的提示词。

# 技能的简要作用描述，Agent所有可选技能与工具的简要描述会被组装在available_skills_and_tools中
use_guide:
  skill_name: "planning"
  description:
    "
    该技能用于规划Agent的step。
    planning技能可以为Agent追加需要执行的多个新的step。
    planning是Agent自主决定自身工作逻辑与自主决定使用什么工具与技能的重要实现方式之一。
    "

# 技能实际调用的提示词
use_prompt:
  skill_name: "planning"
  skill_prompt:
    "
    **你现在正在执行规划技能，你需要根据当前Agent被分配的stage目标，来规划多个step以完成该目标。**
    step是Agent执行的最小单位，每个step只包含一次skill或tool的调用（可选skill与tool见 available_skills_and_tools）。
    请根据当前stage目标，规划多个step以完成该目标（规划的最后一个step应当是一个reflection step）。
    **你必须清楚考虑每个step所需要的前置信息，必要时候先使用ask_info等技能获取MAS内的信息。**
    你将按照 return_format 的返回格式信息，将规划好的step信息按照 return_format 指导的形式给出。
    通过 return_format 中的方式来具为Agent添加新的step.
    "
  return_format: |
    - 输出格式为完成多个的step顺序组成的列表 List[Dict[str,str]]，列表中的每个字典表示你规划的一个step。你生成的每个step要包含以下字段并填充具体值：
      step_intention (str): 步骤的简要意图
      type (str): 步骤的类型,例如：'skill', 'tool'
      executor (str): 执行该步骤的对象，如果是 type 是 'tool' 则填工具名称，如果是 'skill' 则填技能名称
      text_content (Optional[str]): 
        如果是使用技能，则必须填入技能调用的提示文本（不是Skill规则的系统提示，而是需要这个skill做什么具体任务的目标提示文本）
        如果该步骤是用来获取信息的，请在该字段明确写明这点，并且指示该信息添加到你的持续性记忆中（如果不添加到持续性记忆中一般将丢失该信息）
        
    - 请将你规划的结果(由多个step字典组成的列表)收尾用<planned_step>和</planned_step>标记，不要将其放在代码块中：
    <planned_step>
    [
      <Step_Dict>,
      <Step_Dict>,
      ...
    ]
    </planned_step>
    
    - **规划结果首尾用<planned_step>和</planned_step>标记，不要将其放在代码块中，否则将无法被系统识别。**返回示例：
    <planned_step>
    [
      {
        "step_intention": "获取当前时间",
        "type": "tool",
        "executor": "time_tool",
        "text_content": "获取当前时间"
      },
      {
        "step_intention": "获取天气",
        "type": "tool",
        "executor": "weather_tool",
        "text_content": "获取当前天气"
      }
    ]
    </planned_step>
  






