# Date: 2025/04/18
# 该文件用于描述技能的使用方法，以及技能包含的提示词。

# 技能的简要作用描述，Agent所有可选技能与工具的简要描述会被组装在available_skills_and_tools中
use_guide:
  skill_name: "process_message"
  description: |
    **process_message技能禁止Agent主动为自己添加！！！**
    该技能主要用读取其他Agent发送的不需要回复的消息。
    **任何情况下process_message都不应当由决策技能主动规划，而一般由其他Agent向你发送消息后系统帮你自动添加该步骤用于确保读取消息。**
    **如果Agent的决策技能主动为自己规划了process_message步骤，则会导致实际执行中重复执行process_message。**
    在该技能中，Agent会调用LLM总结并消化来自其他Agent的文本消息，并且将消化结果添加在持续性记忆中。
    
    在MAS中Agent间通讯的类型有两种实现方式：
    - 一个单向消息：发起者执行Send Message技能，接收者被添加Process Message步骤以读取信息；
    - 长期多轮对话：发起者执行Send Message技能，接收者被添加Send Message步骤以回复该消息。

# 技能实际调用的提示词
use_prompt:
  skill_name: "process_message"
  skill_prompt: |
    **你现在正在执行process_message技能，你正在接收来自其他Agent的消息。**
    你需要对接收到的来自其他Agent的消息进行消化与整理，**同时判断你需不需要根据消息内容做出行为反应**。
    (一些消息只是告知性质的交流，通常不需要做出行为反应，请勿滥用行为反应功能。但有一些消息会指导/干预你的行为，你需要做出相应的行为反应。)
    参考已执行的历史step信息和待执行的step信息(见 history_step 章节) ，准确理解并消化当前step中记录的有关接收到的消息内容(接收到的消息内容见当前step的text_content)。
    将整理后的消息内容以 return_format 的格式输出，**并且将你认为其中重要的部分添加到你的持续性记忆中**。
    
    如果你认为需要对消息做出行为反应，你会被追加插入一个Decision Step来赋予你接下来短期行为能力，因此你需要生成创建该Decision Step的指令：
      你需要确定以下两个字段的内容（你填入的意图说明越准确你完成该行为反应的成功率越高）：
        step_intention 用于规划相应行为的简要意图。
        text_content 用于描述规划意图的详细说明。
      你需要将这两个字段的内容放在<react_action>和</react_action>标记中(详见 return_format 部分)。

  return_format: |
    - **请将你处理的消息结果用<process_message>和</process_message>标记，不要将其放在代码块中，否则将无法被系统识别。**返回示例：
      
      一. 如果你认为只需要对消息理解消化，不需要做出行为反应，则示例：
      <process_message>你对接收到消息的理解与消化</process_message>
      
      二. 如果你认为需要对消息做出行为反应，则同时给出<process_message>消化内容和<react_action>行为反应指令，一个示例：
      <process_message>你对接收到消息的理解与消化</process_message>
      <react_action>
      {
        "step_intention": "规划获取帮助文档指定信息的步骤",
        "text_content": "接收到来自管理Agent的消息，要求我按照'帮助文档'的内容来执行手中的合同审查任务。我需要规划一些步骤来获取帮助文档中的相关信息。其中帮助文档位于......",
      }
      </react_action>