# Date: 2025/05/13
# 该文件用于描述技能的使用方法，以及技能包含的提示词。

# 技能的简要作用描述，Agent所有可选技能与工具的简要描述会被组装在available_skills_and_tools中

use_guide:
  skill_name: "tool_decision"
  description: |
    **tool_decision技能不允许在Planning/Reflection时由Agent主动使用！！**
    该技能负责调用LLM接收并处理长尾工具的返回结果，
    并决定下一步该工具的执行（指导指令生成步骤）或是结束长尾工具调用。
    
    该技能的触发只由长尾工具主动触发
    （长尾工具是指同一个工具的连续多次调用，需要由LLM不断判断每一步工具使用的方向）
    **tool_decision技能不允许在Planning/Reflection时由Agent主动使用！！**

# 技能实际调用的提示词  TODO：skill_prompt和return_format提示词
use_prompt:  
  skill_name: "tool_decision"  
  skill_prompt: |
    **你现在正在执行tool_decision技能，你需要分析长尾工具的返回结果（工具返回结果于"history_tools_result"中）并决定下一步该工具的执行（指导指令生成步骤）或是结束长尾工具调用。**
        
    结合工具调用的最初意图,该工具的历史长尾调用结果

    **根据你当前步骤意图，仔细按照return_format中的格式返回具体指令**

  return_format: |
    **输出工具决策指令格式为字典，根据你的决策填充适当的字段：**
    
    - 如果决定继续调用工具，需要填充以下字段：
      # 下面是继续调用工具的JSON格式
      # action：设置为"continue"
      # tool_name：下一步要调用的工具名称
      # tool_params：工具参数提示，用于指导InstructionGeneration生成具体参数
      # previous_result：可选，可以包含对上一个工具结果的简要总结
      # reason：为什么需要继续调用此工具的原因
      {
        "action": "continue",
        "tool_name": "<tool_name>",
        "tool_params": {
          "param1": "value1",
          "param2": "value2"
        },
        "previous_result": "<previous_result>",
        "reason": "<reason>"
      }
    
    - 如果决定结束工具调用流程，需要填充以下字段：
      # 下面是结束工具调用的JSON格式
      # action：设置为"terminate"
      # result：最终结果的摘要
      # reason：结束工具调用的原因
      {
        "action": "terminate",
        "result": "<r>",
        "reason": "<reason>"
      }
    
    **请将你的指令构造结果用<tool_decision>和</tool_decision>标记，不要将其放在代码块中，否则将无法被系统识别。**返回示例： 
     <tool_decision>
     具体工具调用决策...
     </tool_decision>
