# Date: 2025/04/09
# 该文件用于描述工具的使用方法，以及调用工具的配置信息

# Configuration for the Milvus Vector Database tool
vector_db_config:
  connection:
    host: "43.142.97.170"
    port: "19530"
    alias: "default"
    timeout: 10
    max_retries: 3
  embedding:
    model_name: "all-mpnet-base-v2"  #TODO: enbedding模型待选型测试
  collection:
    index_type: "IVF_FLAT"
    metric_type: "L2"
    nlist: 1024
    nprobe: 10
    vector_dim: 768
    max_length: 65535


use_guide:
  tool_name: "milvus_vector_db"
  description:
    "
    一个使用Milvus的向量数据库工具，提供文档存储和相似性搜索功能。
    "
use_prompt:
  tool_name: "milvus_vector_db"
  tool_prompt: |
    "你正在帮助生成Milvus向量数据库工具的指令。
    该工具可以：
    1. 通过将文档转换为向量并存储在Milvus中
    2. 使用向量相似度搜索相似文档
    3. 根据相似性得分检索文档

    请格式化指令以指定：
    - 操作类型（store/search)
    - 文档内容或查询
    - Milvus中的Collection名称
    - 返回的结果数量"

  return_format: |
    # Milvus工具指令格式

    指令必须按照以下格式编写：

    <MILVUS>
    {
      "operation": "[store|search]",  # 要执行的操作类型
      "content": "text content or query",   # 文档文本（用于存储）或搜索查询（用于搜索）
      "collection_name": "collection_name", # Milvus 中的collection名称
      "top_k": number  # 可选，结果数量 (1-100)，默认为 5
    }
    </MILVUS>

    要求：
    1. operation 必须是以下之一：store（保存文档）、search（查找相似文档）
    2. content 必须提供，且不超过 65535 个字符
    3. collection_name 必须是有效的字母数字组合字符串，如 "docs2025"
       - collection_name 只能包含字母、数字和下划线
       - collection_name 必须以字母开头
       - collection_name 的长度必须在 1 到 255 个字符之间
       - collection_name 不能包含空格或特殊字符
    4. top_k 是可选的，如果提供，则必须介于 1 和 100 之间

    示例：
    1. 存储文档：
    <MILVUS>
    {
    "operation": "store",
    "content": "这是一个用于存储在向量数据库中的示例文档。",
    "collection_name": "docs2025"
    }
    </MILVUS>

    2. 搜索相似文档：
    <MILVUS>
    {
    "operation": "search",
    "content": "示例文档在向量数据库中",
    "collection_name": "docs2025",
    "top_k": 3
    }
    </MILVUS>


