# MCP服务名称，与AgentState.tools中工具权限名称一致
name: "playwright",
# MCP服务配置，标准MCP配置格式，由服务端提供
config: {
  "mcpServers": {
    "playwright": {
      "command": "npx",
      "args": [
        "@playwright/mcp@latest"
      ]
    }
  }
}
