api_type: "openai"
base_url: "http://localhost:4141/v1"  # 指向本地代理服务
model: "gpt-4.1" #"claude-sonnet-4" #"gpt-4.1"
api_key: "dummy_key"  # 可以使用任意字符串，代理会处理认证
max_tokens: 8192
temperature: 0.1
timeout: 600